name: dmfa
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - jupyter
  - jupyterlab
  - ipykernel
  - ipympl
  - ipywidgets
  - openpyxl